# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/aporeto-inc/addedeffect"
  version = "8.10.0"

[[constraint]]
  name = "github.com/aporeto-inc/gaia"
  version = "9.6.0"

[[constraint]]
  name = "github.com/aporeto-inc/midgard-lib"
  version = "7.2.0"

[[constraint]]
  name = "github.com/aporeto-inc/tg"
  version = "2.33.0"

[[constraint]]
  name = "github.com/aporeto-inc/underwater"
  version = "10.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/buger/goterm"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-wordwrap"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[prune]
  go-tests = true
  unused-packages = true
